### ISSUE TITLE
При деплое функции не подхватывает сервисный аккаунт

### ISSUE THREAD

**Issue by D1ver** [yc-actions/yc-sls-function#353]
Такой конфиг

```
       - name: Deploy Data* Function
         id: data****
         uses: yc-actions/yc-sls-function@v2
         with:
           yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}          
           folder-id: 'b1g2t4te****'
           function-name: 'data****'
           runtime: 'python311'
           memory: '256Mb'
           execution-timeout: '10'
           entrypoint: 'data****.handler'
           source-root: './functions/data****/'
           service-account: 'aje9obc8drds****'
```

Выдает ошибку, не принимает айдишку сервисного аккаунт, хотя у него есть права admin
```
Annotations
1 error
build
ClientError: /yandex.cloud.serverless.functions.v1.FunctionService/CreateVersion INVALID_ARGUMENT: Service account aje9obc8dr***** is not available
```
