### ISSUE TITLE
Ошибка при деплое Api Gateway

### ISSUE THREAD

**Issue by D1ver** [yc-actions/yc-sls-function#354]
Конфиг:
 ```
      - name: Deploy API Gateway
         id: gateway
         uses: yc-actions/yc-apigw-action-deploy@v2.0.0
         with:
           yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
           gateway-name: 'name***'
           folder-id: 'b1g2t4te391****'
           spec-file: './foldername***/name***.yaml'
```

Выдает ошибку, хотя файл лежит в папке
`Unable to resolve action yc-actions/yc-apigw-action-deploy, repository not found`

Лог:
```
Current runner version: '2.302.1'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action yc-actions/yc-apigw-action-deploy, repository not found
```
