### ISSUE TITLE
Поддержка Lockbox

### ISSUE THREAD

**Issue by Inv1x** [yc-actions/yc-sls-function#355]
Сейчас приходится использовать отдельный action для получения секретов из Lockbox, а затем их пробрасывать как environment variable. При этом далеко не все значения, приходящие из Lockbox, могут записаться. Было бы круто, если бы была возможность указать именно lockbox переменные

<img width="1034" alt="Снимок экрана 2023-03-19 в 0 08 31" src="https://user-images.githubusercontent.com/78815019/226140182-608db3a0-ceda-4e70-8c03-f6b5fa3e0a0c.png">
<img width="541" alt="Снимок экрана 2023-03-19 в 0 10 09" src="https://user-images.githubusercontent.com/78815019/226140249-3f33b449-4f2e-440a-af57-2baa63a5e9dd.png">

**Comment by nikolaymatrosov** [comment]
Пришлёте PR? Ну или хотя бы пример того, как бы вы хотели описывать эти значения в action'е?

**Comment by Inv1x** [comment]
Например:
```
yc-sa-json-credentials: 'credentials'
...
lockbox-secrets:
- name-in-function: 'test1'
  secret_id: 'some_id'
  version_id: 'ver_id'
  key: 'key'
- name-in-function: 'test2'
  secret_id: 'some_id'
  version_id: 'ver_id'
  key: 'key'
```
Конкретно сейчас набросить код для подобного не могу, но я надеюсь, что написал понятно и идея видна
