### ISSUE TITLE
Добавить возможность указывать для функции параметры асинхронного вызова

### ISSUE THREAD

**Issue by dolzhikov-vladimir** [yc-actions/yc-sls-function#793]
Добавить параметр асинхронности при создании версии:

https://yandex.cloud/ru/docs/functions/functions/api-ref/Function/createVersion#yandex.cloud.serverless.functions.v1.AsyncInvocationConfig

**Comment by dolzhikov-vladimir** [comment]
Как вариант решения, можно JSON payload указывать в конфиге экшена: 

```
- name: Deploy Function
      id: sls-func
      uses: yc-actions/yc-sls-function@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        bucket: ${{ secrets.BUCKET }}
        folder-id: 'b1g*********'
        async-mode: 'True'
        async-config: ${{ secrets.ASYNC_JSON_CONFIG }}
        folder-id: 'b1g*********'
```

Где ${{ secrets.ASYNC_JSON_CONFIG }} хранится в vars как JSON:

```
"asyncInvocationConfig": {
      "retriesCount": "string",
      "successTarget": {
        // Includes only one of the fields `emptyTarget`, `ymqTarget`
        "emptyTarget": "object",
        "ymqTarget": {
          "queueArn": "string",
          "serviceAccountId": "string"
        }
        // end of the list of possible fields
      },
      "failureTarget": {
        // Includes only one of the fields `emptyTarget`, `ymqTarget`
        "emptyTarget": "object",
        "ymqTarget": {
          "queueArn": "string",
          "serviceAccountId": "string"
        }
        // end of the list of possible fields
      },
      "serviceAccountId": "string"
    },
```

**Comment by nikolaymatrosov** [comment]
Нет. Это абсолютно идет в разрез с тем как задаются параметры сейчас.

**Comment by dolzhikov-vladimir** [comment]
Тогда предлагаю другое задание параметров.
В зависимости от уровня подготовки пользователя, настройка асинхронности может быть как простой, так и расширенной:

1) Для начинающих пользователей (упрощенный режим). Пользователю не нужно логировать результат и он указывает только обязательные параметры (в gui это "Количество повторных попыток"). Остальные параметры асинхронности при этом пользователь может не указывать. Пример:
```
- name: Deploy Function
      id: sls-func
      uses: yc-actions/yc-sls-function@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        bucket: ${{ secrets.BUCKET }}
        folder-id: 'b1g*********'
        async-retries-count: 3
        folder-id: 'b1g*********'
```

2) Для продвинутых пользователей (расширенный режим). Пользователь может детально настроить асинхронность, указав дополнительные параметры, например, очереди для сохранения результатов успешного или неудачного выполнения функции. Пример:
```
- name: Deploy Function
      id: sls-func
      uses: yc-actions/yc-sls-function@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        bucket: ${{ secrets.BUCKET }}
        folder-id: 'b1g*********'
        async-retries-count: 3
        async-success-target-type: ymq
        async-success-target-ymq-queue-arn: [очередь для сохранения результата выполнения]
        async-success-target-ymq-service-account-id: [сервисный аккаунт]
        async-failure-target-type: ymq
        async-failure-target-ymq-queue-arn: [очередь для сохранения результата выполнения]
        async-failure-target-ymq-service-account-id: [сервисный аккаунт]
        folder-id: 'b1g*********'
```

Итого:
Если пользователь хочет включить асинхронную конфигурацию, он должен указать **async-retries-count**.
Если пользователь выбирает **ymq** для **async-success-target-type** или **async-failure-target-type**, он должен указать соответствующие параметры **queue-arn** и **service-account-id**.
Если пользователь выбирает **empty** для **async-success-target-type** или **async-failure-target-type**, дополнительные параметры указывать не нужно:
```
- name: Deploy Function
      id: sls-func
      uses: yc-actions/yc-sls-function@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        bucket: ${{ secrets.BUCKET }}
        folder-id: 'b1g*********'
        async-retries-count: 3
        async-success-target-type: ymq
        async-success-target-ymq-queue-arn: [очередь для сохранения результата выполнения]
        async-success-target-ymq-service-account-id: [сервисный аккаунт]
        async-failure-target-type: empty
        folder-id: 'b1g*********'
```
